name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "feat: ${{ github.ref_name }}"
          body: |
            ## Changes
            Branch: ${{ github.ref_name }}
            
            Automatically created PR from ${{ github.ref_name }} to main
            
            ## Checklist
            - [ ] Code follows the style guidelines
            - [ ] Tests passed
            - [ ] Documentation updated
          draft: false 